name: First Workflow

on:
    push:
        branches:
            -main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: ations/checkout@v2
            
          - name: Display a message
            run: echo "Hello, Github Actions!"